M48
; DRILL file {KiCad (6.0.6)} date Tue Mar 14 09:52:24 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-14T09:52:24+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X3.91Y-3.25
X4.062Y-3.252
T2
X3.55Y-3.25
X3.69Y-3.25
X3.83Y-3.25
X4.45Y-3.25
X4.59Y-3.25
T0
M30
